from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('acerca-de/', views.acerca_de, name='acerca_de'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('productos/', views.productos, name='productos'),
    path('producto/<int:producto_id>/', views.producto_detalle, name='producto_detalle'),
    path('comprar/<int:producto_id>/', views.comprar, name='comprar'),
    path('recomendaciones/', views.recomendaciones, name='recomendaciones'),
    path('carrito/', views.ver_carrito, name='ver_carrito'),
    path('carrito/agregar/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/eliminar/<int:item_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('carrito/actualizar/<int:item_id>/', views.actualizar_carrito, name='actualizar_carrito'),
    path('carrito/vaciar/', views.vaciar_carrito, name='vaciar_carrito'),
    # Checkout
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/direccion/', views.checkout_direccion, name='checkout_direccion'),
    path('checkout/pago/', views.checkout_pago, name='checkout_pago'),
    path('checkout/confirmacion/', views.checkout_confirmacion, name='checkout_confirmacion'),
    path('checkout/procesar/', views.procesar_pedido, name='procesar_pedido'),
    path('pedido/<int:pedido_id>/', views.pedido_detalle, name='pedido_detalle'),
    path('historial-pedidos/', views.historial_pedidos, name='historial_pedidos'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('cambiar-password/', views.cambiar_password, name='cambiar_password'),
    # Reseñas
    path('producto/<int:producto_id>/resena/', views.agregar_resena, name='agregar_resena'),
    path('producto/<int:producto_id>/resenas/', views.ver_resenas, name='ver_resenas'),
    # Cupones
    path('aplicar-cupon/', views.aplicar_cupon, name='aplicar_cupon'),
    path('remover-cupon/', views.remover_cupon, name='remover_cupon'),
    path('cupones/', views.cupones_disponibles, name='cupones_disponibles'),
    # Administración de inventario (ruta separada para evitar conflictos con Django admin)
    path('inventario/', views.admin_inventario, name='inventario_publico'),
    path('inventario/actualizar/<int:producto_id>/', views.actualizar_stock, name='actualizar_stock'),
    path('inventario/movimientos/', views.movimientos_inventario, name='movimientos_inventario'),
    # Sistema de Administración Personalizado
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/productos/', views.admin_productos, name='admin_productos'),
    path('admin/productos/agregar/', views.admin_agregar_producto, name='admin_agregar_producto'),
    path('admin/productos/editar/<int:producto_id>/', views.admin_editar_producto, name='admin_editar_producto'),
    path('admin/productos/eliminar/<int:producto_id>/', views.admin_eliminar_producto, name='admin_eliminar_producto'),
    path('admin/productos/actualizar-stock/', views.admin_actualizar_stock, name='admin_actualizar_stock'),
    path('admin/pedidos/', views.admin_pedidos, name='admin_pedidos'),
    path('admin/pedidos/<int:pedido_id>/', views.admin_detalle_pedido, name='admin_detalle_pedido'),
    path('admin/pedidos/actualizar-estado/', views.admin_cambiar_estado_pedido, name='admin_actualizar_estado_pedido'),
    path('admin/usuarios/', views.admin_usuarios, name='admin_usuarios'),
    path('admin/usuarios/agregar/', views.admin_agregar_usuario, name='admin_agregar_usuario'),
    path('admin/usuarios/editar/<int:usuario_id>/', views.admin_editar_usuario, name='admin_editar_usuario'),
    path('admin/usuarios/<int:usuario_id>/', views.admin_detalle_usuario, name='admin_detalle_usuario'),
    path('admin/usuarios/actualizar-estado/', views.admin_cambiar_estado_usuario, name='admin_actualizar_estado_usuario'),
    path('admin/cupones/', views.admin_cupones, name='admin_cupones'),
    path('admin/cupones/agregar/', views.admin_agregar_cupon, name='admin_agregar_cupon'),
    path('admin/cupones/editar/<int:cupon_id>/', views.admin_editar_cupon, name='admin_editar_cupon'),
    path('admin/cupones/eliminar/<int:cupon_id>/', views.admin_eliminar_cupon, name='admin_eliminar_cupon'),
    path('admin/cupones/actualizar-estado/', views.admin_cambiar_estado_cupon, name='admin_actualizar_estado_cupon'),
    path('admin/inventario/', views.admin_inventario, name='admin_inventario'),
    path('admin/inventario/actualizar/', views.admin_actualizar_inventario, name='admin_actualizar_inventario'),
    path('admin/reportes/', views.admin_reportes, name='admin_reportes'),
    path('admin/configuracion/', views.admin_configuracion, name='admin_configuracion'),
    path('admin/configuracion/guardar/', views.admin_guardar_configuracion, name='admin_guardar_configuracion'),
    path('admin/configuracion/restaurar/', views.admin_restaurar_configuracion, name='admin_restaurar_configuracion'),
    path('admin/backup/', views.admin_crear_backup, name='admin_crear_backup'),
    path('admin/email/test/', views.admin_probar_email, name='admin_probar_email'),
]