from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('acerca-de/', views.acerca_de, name='acerca_de'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('productos/', views.productos, name='productos'),
    path('producto/<int:producto_id>/', views.producto_detalle, name='producto_detalle'),
    path('comprar/<int:producto_id>/', views.comprar, name='comprar'),
    path('recomendaciones/', views.recomendaciones, name='recomendaciones'),
    path('carrito/', views.ver_carrito, name='ver_carrito'),
    path('carrito/agregar/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/eliminar/<int:item_id>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('carrito/actualizar/<int:item_id>/', views.actualizar_carrito, name='actualizar_carrito'),
    path('carrito/vaciar/', views.vaciar_carrito, name='vaciar_carrito'),
    # Checkout
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/direccion/', views.checkout_direccion, name='checkout_direccion'),
    path('checkout/pago/', views.checkout_pago, name='checkout_pago'),
    path('checkout/confirmacion/', views.checkout_confirmacion, name='checkout_confirmacion'),
    path('checkout/procesar/', views.procesar_pedido, name='procesar_pedido'),
    path('pedido/<int:pedido_id>/', views.pedido_detalle, name='pedido_detalle'),
    path('historial-pedidos/', views.historial_pedidos, name='historial_pedidos'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('cambiar-password/', views.cambiar_password, name='cambiar_password'),
    # Reseñas
    path('producto/<int:producto_id>/resena/', views.agregar_resena, name='agregar_resena'),
    path('producto/<int:producto_id>/resenas/', views.ver_resenas, name='ver_resenas'),
    # Cupones
    path('aplicar-cupon/', views.aplicar_cupon, name='aplicar_cupon'),
    path('remover-cupon/', views.remover_cupon, name='remover_cupon'),
    path('cupones/', views.cupones_disponibles, name='cupones_disponibles'),
    # Administración de inventario (ruta separada para evitar conflictos con Django admin)
    path('inventario/', views.admin_inventario, name='inventario_publico'),
    path('inventario/actualizar/<int:producto_id>/', views.actualizar_stock, name='actualizar_stock'),
    path('inventario/movimientos/', views.movimientos_inventario, name='movimientos_inventario'),
    # Sistema de Lista de Deseos (Wishlist)
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/agregar/<int:producto_id>/', views.agregar_a_wishlist, name='agregar_a_wishlist'),
    path('wishlist/quitar/<int:producto_id>/', views.quitar_de_wishlist, name='quitar_de_wishlist'),
    path('wishlist/toggle/<int:producto_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('wishlist/count/', views.wishlist_count, name='wishlist_count'),
    # Sistema de Contribuciones a Wishlist
    path('wishlists-contribuciones/', views.wishlists_con_contribuciones, name='wishlists_con_contribuciones'),
    path('wishlist/<int:wishlist_id>/contribucion/', views.wishlist_detalle_contribucion, name='wishlist_detalle_contribucion'),
    path('wishlist/<int:wishlist_id>/contribuir/', views.contribuir_wishlist, name='contribuir_wishlist'),
    path('wishlist/<int:wishlist_id>/gestionar-contribuciones/', views.gestionar_contribuciones_wishlist, name='gestionar_contribuciones_wishlist'),
    path('historial-contribuciones/', views.historial_contribuciones, name='historial_contribuciones'),
    path('contribucion/<int:contribucion_id>/pago/', views.pago_contribucion, name='pago_contribucion'),
    path('contribucion/<int:contribucion_id>/procesar-pago/', views.procesar_pago_contribucion, name='procesar_pago_contribucion'),
    # Sistema de Comparación de Productos
    path('comparacion/', views.comparacion_productos, name='comparacion_productos'),
    path('comparacion/agregar/<int:producto_id>/', views.agregar_a_comparacion, name='agregar_a_comparacion'),
    path('comparacion/quitar/<int:producto_id>/', views.quitar_de_comparacion, name='quitar_de_comparacion'),
    path('comparacion/limpiar/', views.limpiar_comparacion, name='limpiar_comparacion'),
    path('comparacion/toggle/<int:producto_id>/', views.toggle_comparacion, name='toggle_comparacion'),
    path('comparacion/count/', views.comparacion_count, name='comparacion_count'),
    # Sistema de Puntos de Fidelidad
    path('puntos-fidelidad/', views.puntos_fidelidad, name='puntos_fidelidad'),
    path('puntos-fidelidad/historial/', views.historial_puntos, name='historial_puntos'),
    path('puntos-fidelidad/canjear/', views.canjear_puntos, name='canjear_puntos'),
    # Sistema de Newsletter
    path('newsletter/suscribir/', views.suscribir_newsletter, name='suscribir_newsletter'),
    path('newsletter/confirmar/<str:token>/', views.confirmar_newsletter, name='confirmar_newsletter'),
    path('newsletter/cancelar/', views.cancelar_newsletter, name='cancelar_newsletter'),
    path('newsletter/unsubscribe/<str:email_b64>/', views.newsletter_unsubscribe_direct, name='newsletter_unsubscribe_direct'),
    # Administración de Newsletter
    path('admin/newsletter/', views.admin_newsletter, name='admin_newsletter'),
    path('admin/newsletter/suscriptores/', views.admin_newsletter_suscriptores, name='admin_newsletter_suscriptores'),
    path('admin/newsletter/campanas/', views.admin_newsletter_campanas, name='admin_newsletter_campanas'),
    path('admin/newsletter/campanas/crear/', views.admin_crear_campana, name='admin_crear_campana'),
    path('admin/newsletter/campanas/editar/<int:campana_id>/', views.admin_editar_campana, name='admin_editar_campana'),
    path('admin/newsletter/campanas/enviar/<int:campana_id>/', views.admin_enviar_campana, name='admin_enviar_campana'),
    path('admin/newsletter/campanas/enviar-directo/<int:campana_id>/', views.admin_enviar_campana_directo, name='admin_enviar_campana_directo'),
    path('admin/newsletter/campanas/test/<int:campana_id>/', views.admin_test_campana, name='admin_test_campana'),
    path('admin/newsletter/campanas/eliminar/<int:campana_id>/', views.admin_eliminar_campana, name='admin_eliminar_campana'),
    path('admin/newsletter/campanas/cancelar/<int:campana_id>/', views.admin_cancelar_campana, name='admin_cancelar_campana'),
    path('admin/newsletter/campanas/duplicar/<int:campana_id>/', views.admin_duplicar_campana, name='admin_duplicar_campana'),
    path('admin/newsletter/suscriptores/activar/<int:suscriptor_id>/', views.admin_activar_suscriptor, name='admin_activar_suscriptor'),
    path('admin/newsletter/suscriptores/desactivar/<int:suscriptor_id>/', views.admin_desactivar_suscriptor, name='admin_desactivar_suscriptor'),
    path('admin/newsletter/suscriptores/eliminar/<int:suscriptor_id>/', views.admin_eliminar_suscriptor, name='admin_eliminar_suscriptor'),
    path('admin/newsletter/suscriptores/reenviar/<int:suscriptor_id>/', views.admin_reenviar_confirmacion, name='admin_reenviar_confirmacion'),
    path('admin/newsletter/suscriptores/exportar/', views.admin_exportar_suscriptores, name='admin_exportar_suscriptores'),
    path('admin/newsletter/enviar-test/', views.admin_enviar_test_newsletter, name='admin_enviar_test_newsletter'),
    # Tracking de Newsletter
    path('newsletter/tracking/open/<int:log_id>/', views.tracking_newsletter_open, name='tracking_newsletter_open'),
    path('newsletter/tracking/click/<int:log_id>/<path:url>/', views.tracking_newsletter_click, name='tracking_newsletter_click'),
    # Recuperación de contraseña
    path('password-reset/', views.password_reset_request, name='password_reset_request'),
    path('password-reset/done/', views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
    # Dashboard de Reportes de Email
    path('admin/email-dashboard/', views.admin_email_dashboard, name='admin_email_dashboard'),
    path('admin/email/<int:email_id>/', views.admin_email_detalle, name='admin_email_detalle'),
    path('admin/email/<int:email_id>/reenviar/', views.admin_email_reenviar, name='admin_email_reenviar'),
    path('admin/newsletter-dashboard/', views.admin_newsletter_dashboard, name='admin_newsletter_dashboard'),
    # Sistema de Administración Personalizado (movido al admin site personalizado)
    # path('admin/', views.admin_dashboard, name='admin_dashboard'),
    # path('admin/productos/', views.admin_productos, name='admin_productos'),
    # path('admin/productos/agregar/', views.admin_agregar_producto, name='admin_agregar_producto'),
    # path('admin/productos/editar/<int:producto_id>/', views.admin_editar_producto, name='admin_editar_producto'),
    # path('admin/productos/eliminar/<int:producto_id>/', views.admin_eliminar_producto, name='admin_eliminar_producto'),
    # path('admin/productos/actualizar-stock/', views.admin_actualizar_stock, name='admin_actualizar_stock'),
    # path('admin/pedidos/', views.admin_pedidos, name='admin_pedidos'),
    # path('admin/pedidos/<int:pedido_id>/', views.admin_detalle_pedido, name='admin_detalle_pedido'),
    # path('admin/pedidos/actualizar-estado/', views.admin_cambiar_estado_pedido, name='admin_actualizar_estado_pedido'),
    # path('admin/usuarios/', views.admin_usuarios, name='admin_usuarios'),
    # path('admin/usuarios/agregar/', views.admin_agregar_usuario, name='admin_agregar_usuario'),
    # path('admin/usuarios/editar/<int:usuario_id>/', views.admin_editar_usuario, name='admin_editar_usuario'),
    # path('admin/usuarios/<int:usuario_id>/', views.admin_detalle_usuario, name='admin_detalle_usuario'),
    # path('admin/usuarios/actualizar-estado/', views.admin_cambiar_estado_usuario, name='admin_actualizar_estado_usuario'),
    # path('admin/cupones/', views.admin_cupones, name='admin_cupones'),
    # path('admin/cupones/agregar/', views.admin_agregar_cupon, name='admin_agregar_cupon'),
    # path('admin/cupones/editar/<int:cupon_id>/', views.admin_editar_cupon, name='admin_editar_cupon'),
    # path('admin/cupones/eliminar/<int:cupon_id>/', views.admin_eliminar_cupon, name='admin_eliminar_cupon'),
    # path('admin/cupones/actualizar-estado/', views.admin_cambiar_estado_cupon, name='admin_actualizar_estado_cupon'),
    # path('admin/inventario/', views.admin_inventario, name='admin_inventario'),
    # path('admin/inventario/actualizar/', views.admin_actualizar_inventario, name='admin_actualizar_inventario'),
    # path('admin/reportes/', views.admin_reportes, name='admin_reportes'),
    # path('admin/configuracion/', views.admin_configuracion, name='admin_configuracion'),
    # path('admin/configuracion/guardar/', views.admin_guardar_configuracion, name='admin_guardar_configuracion'),
    # path('admin/configuracion/restaurar/', views.admin_restaurar_configuracion, name='admin_restaurar_configuracion'),
    # path('admin/backup/', views.admin_crear_backup, name='admin_crear_backup'),
    # path('admin/email/test/', views.admin_probar_email, name='admin_probar_email'),
]