# Generated by Django 5.2.6 on 2025-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_options_producto_dimensiones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_activo', models.BooleanField(default=True, help_text='Si el sitio web está activo')),
                ('registro_abierto', models.BooleanField(default=True, help_text='Permitir registro de nuevos usuarios')),
                ('moneda', models.CharField(default='COP', help_text='Moneda predeterminada (COP, USD, EUR)', max_length=3)),
                ('envio_gratuito_minimo', models.DecimalField(decimal_places=2, default=50000, help_text='Monto mínimo para envío gratuito', max_digits=10)),
                ('stock_minimo_alerta', models.PositiveIntegerField(default=5, help_text='Stock mínimo para mostrar alerta')),
                ('productos_por_pagina', models.PositiveIntegerField(default=12, help_text='Productos por página en catálogo')),
                ('impuestos_activos', models.BooleanField(default=True, help_text='Calcular y mostrar impuestos')),
                ('email_notificaciones', models.BooleanField(default=True, help_text='Enviar notificaciones por email')),
                ('email_admin', models.EmailField(blank=True, help_text='Email del administrador', max_length=254)),
                ('email_smtp', models.CharField(blank=True, help_text='Servidor SMTP', max_length=100)),
                ('email_puerto', models.PositiveIntegerField(default=587, help_text='Puerto SMTP')),
                ('email_usuario', models.CharField(blank=True, help_text='Usuario SMTP', max_length=100)),
                ('email_password', models.CharField(blank=True, help_text='Contraseña SMTP', max_length=200)),
                ('session_timeout', models.PositiveIntegerField(default=60, help_text='Tiempo de sesión en minutos')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Máximo intentos de login')),
                ('two_factor_auth', models.BooleanField(default=False, help_text='Autenticación de dos factores para admin')),
                ('password_complexity', models.BooleanField(default=True, help_text='Requerir contraseñas complejas')),
                ('backup_automatico', models.BooleanField(default=True, help_text='Realizar backups automáticos')),
                ('backup_frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=20)),
                ('backup_retencion', models.PositiveIntegerField(default=30, help_text='Días para retener backups')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
