# Generated by Django 5.2.6 on 2025-09-26 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_profile_nivel_membresia_profile_puntos_disponibles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparacionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(blank=True, related_name='comparaciones', to='tienda.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comparación de Productos',
                'verbose_name_plural': 'Comparaciones de Productos',
            },
        ),
    ]
