# Generated by Django 5.2.6 on 2025-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_emailtemplate_emailnotification_emailqueue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='tracking_aperturas',
            field=models.BooleanField(default=True, help_text='Habilitar tracking de aperturas'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='tracking_clics',
            field=models.BooleanField(default=True, help_text='Habilitar tracking de clics'),
        ),
    ]
