# Generated by Django 5.2.6 on 2025-09-26 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_newslettercampaign_tracking_aperturas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='contribucion_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto objetivo para contribuciones grupales', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='contribucion_privada',
            field=models.BooleanField(default=False, help_text='Las contribuciones son privadas (solo visible para el propietario)'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='permitir_contribuciones',
            field=models.BooleanField(default=False, help_text='Permitir que otros usuarios contribuyan al pago'),
        ),
        migrations.CreateModel(
            name='ContribucionWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje opcional del contribuyente', null=True)),
                ('fecha_contribucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('completado', 'Pago Completado'), ('procesado', 'Procesado en Pedido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuciones', to='tienda.pedido')),
                ('usuario_contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones', to='tienda.wishlist')),
            ],
            options={
                'verbose_name': 'Contribución Wishlist',
                'verbose_name_plural': 'Contribuciones Wishlist',
                'ordering': ['-fecha_contribucion'],
            },
        ),
    ]
