# Generated by Django 5.2.6 on 2025-09-26 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_add_wishlist_contributions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='puntos_requeridos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos requeridos para comprar este cupón'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='tipo_cupon',
            field=models.CharField(choices=[('normal', 'Cupón Normal'), ('codigo_copiable', 'Código Copiable'), ('comprado_puntos', 'Comprado con Puntos'), ('canjeado_puntos', 'Canjeado por Puntos')], default='normal', help_text='Tipo de cupón', max_length=20),
        ),
        migrations.AddField(
            model_name='cupon',
            name='usado_por_usuario',
            field=models.BooleanField(default=False, help_text='Si este cupón ya fue usado por su propietario'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='usuario_propietario',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario (para cupones personales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PedidoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, help_text='Descuento aplicado por este cupón', max_digits=10)),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_usados', to='tienda.cupon')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones_aplicados', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Cupón del Pedido',
                'verbose_name_plural': 'Cupones del Pedido',
                'unique_together': {('pedido', 'cupon')},
            },
        ),
    ]
