# Generated by Django 5.2.6 on 2025-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_cupon_puntos_requeridos_cupon_tipo_cupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='descripcion_contribucion',
            field=models.TextField(blank=True, help_text='Descripción opcional de la contribución grupal', null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de última modificación de la configuración de contribuciones'),
        ),
    ]
