# Generated by Django 5.2.6 on 2025-09-26 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_wishlist_descripcion_contribucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='codigo_referido',
            field=models.CharField(blank=True, help_text='Código único para tracking de referidos', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='compartir_activo',
            field=models.BooleanField(default=True, help_text='Permitir compartir esta wishlist en redes sociales'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='veces_compartido',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que se ha compartido'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='veces_contribuido_via_referido',
            field=models.PositiveIntegerField(default=0, help_text='Número de contribuciones vía referidos'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='veces_visitado_via_referido',
            field=models.PositiveIntegerField(default=0, help_text='Número de visitas vía enlaces de referido'),
        ),
        migrations.CreateModel(
            name='HistorialCompartir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('email', 'Email'), ('copiar_enlace', 'Copiar Enlace'), ('otro', 'Otro')], max_length=20)),
                ('fecha_compartido', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compartidos', to='tienda.wishlist')),
            ],
            options={
                'verbose_name': 'Historial Compartir',
                'verbose_name_plural': 'Historial Compartidos',
                'ordering': ['-fecha_compartido'],
            },
        ),
        migrations.CreateModel(
            name='ReferidoWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma_origen', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('enlace_compartido', 'Enlace Compartido'), ('email', 'Email'), ('otro', 'Otro')], help_text='Plataforma desde donde vino el referido', max_length=20)),
                ('fecha_referido', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('contribucion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referido_origen', to='tienda.contribucionwishlist')),
                ('usuario_referido', models.ForeignKey(blank=True, help_text='Usuario que llegó por el referido (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_referidor', models.ForeignKey(help_text='Usuario que compartió el enlace', on_delete=django.db.models.deletion.CASCADE, related_name='referidos_enviados', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos', to='tienda.wishlist')),
            ],
            options={
                'verbose_name': 'Referido Wishlist',
                'verbose_name_plural': 'Referidos Wishlist',
                'ordering': ['-fecha_referido'],
            },
        ),
    ]
