# Generated by Django 5.2.6 on 2025-09-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_wishlist_codigo_referido_wishlist_compartir_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='moneda',
            field=models.CharField(default='ARS', help_text='Moneda predeterminada (ARS, COP, USD, EUR)', max_length=3),
        ),
    ]
