# Generated by Django 5.2.6 on 2025-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_change_default_currency_to_ars'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_file',
            field=models.ImageField(blank=True, help_text='Imagen del producto subida al servidor', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='tipo',
            field=models.CharField(choices=[('registro', 'Registro de Usuario'), ('recuperacion', 'Recuperación de Contraseña'), ('pedido_confirmacion', 'Confirmación de Pedido'), ('pedido_actualizacion', 'Actualización de Pedido'), ('pedido_envio', 'Pedido Enviado'), ('pedido_entrega', 'Pedido Entregado'), ('bienvenida', 'Bienvenida'), ('newsletter_bienvenida', 'Bienvenida Newsletter'), ('carrito_abandonado', 'Carrito Abandonado'), ('producto_descuento', 'Producto con Descuento'), ('puntos_acumulados', 'Puntos de Lealtad'), ('contribucion_confirmada', 'Confirmación de Contribución'), ('custom', 'Personalizado')], default='custom', max_length=30),
        ),
    ]
