# Generated by Django 5.2.6 on 2025-09-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_file',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_blob',
            field=models.BinaryField(blank=True, help_text='Imagen del producto almacenada como blob', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo de imagen', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_tipo_mime',
            field=models.CharField(blank=True, help_text='Tipo MIME de la imagen (ej: image/jpeg)', max_length=100, null=True),
        ),
    ]
