# Generated by Django 5.2.6 on 2025-09-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_crear_modelo_imagenes_multiples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
    ]
