# Generated by Django 5.2.6 on 2025-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_alter_producto_categoria_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='contribucion_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto objetivo para contribuciones grupales', max_digits=10),
        ),
    ]
